pipeline {
    agent any
    tools {
        maven 'maven_3_5_0'
    }

    environment {
        DOCKER_IMAGE = "tofazzal/authentication-server:latest"
    }

    stages {
        stage('Build Maven') {
            steps {
                checkout scmGit(
                    branches: [[name: '*/master']], extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/TofazzalTopu/authentication-server']]
                )
            }
        }

        stage('Build Maven') {
            steps {
                sh 'mvn clean install -DskipTests'
            }
        }

        stage ("Build Docker Image"){
            steps{
                script {
                    sh 'docker build -t ${DOCKER_IMAGE} .'
                }
            }
        }

        stage("Push Docker Image To Docker Hub") {
            steps {
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'docker-hub-cred',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PWD'
                    )]) {

                        sh '''
                        echo "$DOCKER_PWD" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push ${DOCKER_IMAGE}
                        '''
                    }
                }
            }
        }


        stage('Deploy to Kubernetes') {
            steps {
                script {
                    // Use kubeconfig stored in Jenkins credentials
                    withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {

                        sh '''
                        export KUBECONFIG=$KUBECONFIG

                        # Apply deployment
                        kubectl apply -f deployment.yml

                        # Ensure latest image is pulled (important for :latest tag)
                        kubectl rollout restart deployment authentication-server

                        # Verify rollout
                        kubectl rollout status deployment authentication-server
                        '''
                    }
                }
            }
        }
    }

}