#spring.application.name=spring-keycloak-service
#keycloak.auth-server-url=http://localhost:8080
#keycloak.realm=master
#keycloak.resource=myclient
#keycloak.public-client=true
#keycloak.use-resource-role-mappings=true
#spring.security.oauth2.client.provider.keycloak.issuer-uri=${keycloak.auth-server-url}/realms/${keycloak.realm}